@startuml Transport system
start
:Passenger arrives at transport connection;
repeat :Passenger waits for the vehicle to arrive;
    :Passenger checks in their rejsekort; 
    :Passenger is in transit;
    :The vehicle goes through its sequential stops;
    :The vehicle stops at the passengers stop;
    repeat while (Passengers end stop?) is (no)
->yes;
    :The passenger checks out;
    :The passenger leaves the transport connection;

stop
@enduml